version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_USER: xmind_user
      POSTGRES_PASSWORD: xmind_password
      POSTGRES_DB: xmind_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - xmind-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic_user
      - ELASTIC_PASSWORD=elastic_password_123
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - xmind-network
    volumes:
      - es-data:/usr/share/elasticsearch/data
volumes:
  postgres-data:
  es-data:

networks:
  xmind-network:
    driver: bridge
